### ISSUE TITLE
gpg failing on swift version 5.0 and 5.1

### ISSUE THREAD

**Issue by marzvrover** [swift-actions/setup-swift#419]
**Describe the bug**
gpg: no valid OpenPGP data found

```
2022-05-27T01:03:18.6540771Z ##[group]Run swift-actions/setup-swift@v1
2022-05-27T01:03:18.6541027Z with:
2022-05-27T01:03:18.6541219Z   swift-version: 5.0
2022-05-27T01:03:18.6541402Z ##[endgroup]
2022-05-27T01:03:19.0435884Z [command]/usr/bin/gpg --import /home/runner/work/_temp/d75c9f8a-9a43-4698-b365-ce3cc73aa4f8
2022-05-27T01:03:19.0520669Z gpg: directory '/home/runner/.gnupg' created
2022-05-27T01:03:19.0523805Z gpg: keybox '/home/runner/.gnupg/pubring.kbx' created
2022-05-27T01:03:19.0554994Z gpg: /home/runner/.gnupg/trustdb.gpg: trustdb created
2022-05-27T01:03:19.0557566Z gpg: key D441C977412B37AD: public key "Swift Automatic Signing Key #1 <swift-infrastructure@swift.org>" imported
2022-05-27T01:03:19.0658866Z gpg: key 9F597F4D21A56D5F: public key "Swift 2.2 Release Signing Key <swift-infrastructure@swift.org>" imported
2022-05-27T01:03:19.0667085Z gpg: key 63BC1CFE91D306C6: public key "Swift 3.x Release Signing Key <swift-infrastructure@swift.org>" imported
2022-05-27T01:03:19.0675426Z gpg: key EF5430F071E1B235: public key "Swift 4.x Release Signing Key <swift-infrastructure@swift.org>" imported
2022-05-27T01:03:19.0685228Z gpg: key 7638F1FB2B2B08C4: public key "Swift Automatic Signing Key #2 <swift-infrastructure@swift.org>" imported
2022-05-27T01:03:19.0694155Z gpg: key 925CC1CCED3D1561: public key "Swift 5.x Release Signing Key <swift-infrastructure@swift.org>" imported
2022-05-27T01:03:19.0703180Z gpg: key FAF6989E1BC16FEA: public key "Swift Automatic Signing Key #3 <swift-infrastructure@swift.org>" imported
2022-05-27T01:03:19.0836806Z gpg: key 925CC1CCED3D1561: "Swift 5.x Release Signing Key <swift-infrastructure@swift.org>" 1 new signature
2022-05-27T01:03:19.0850317Z gpg: key F167DF1ACF9CE069: public key "Swift Automatic Signing Key #4 <swift-infrastructure@forums.swift.org>" imported
2022-05-27T01:03:19.0851037Z gpg: Total number processed: 9
2022-05-27T01:03:19.0865498Z gpg:               imported: 8
2022-05-27T01:03:19.0866138Z gpg:         new signatures: 1
2022-05-27T01:03:19.0885012Z [command]/usr/bin/gpg --keyserver hkp://keyserver.ubuntu.com --refresh-keys Swift
2022-05-27T01:03:19.3445053Z gpg: refreshing 8 keys from hkp://keyserver.ubuntu.com
2022-05-27T01:03:23.0802502Z gpg: key F167DF1ACF9CE069: "Swift Automatic Signing Key #4 <swift-infrastructure@forums.swift.org>" not changed
2022-05-27T01:03:23.0807153Z gpg: key FAF6989E1BC16FEA: "Swift Automatic Signing Key #3 <swift-infrastructure@swift.org>" not changed
2022-05-27T01:03:23.0816091Z gpg: key 925CC1CCED3D1561: "Swift 5.x Release Signing Key <swift-infrastructure@swift.org>" not changed
2022-05-27T01:03:23.0822050Z gpg: key 7638F1FB2B2B08C4: "Swift Automatic Signing Key #2 <swift-infrastructure@swift.org>" not changed
2022-05-27T01:03:23.0828369Z gpg: key EF5430F071E1B235: "Swift 4.x Release Signing Key <swift-infrastructure@swift.org>" not changed
2022-05-27T01:03:23.0834526Z gpg: key 63BC1CFE91D306C6: "Swift 3.x Release Signing Key <swift-infrastructure@swift.org>" not changed
2022-05-27T01:03:23.0840519Z gpg: key 9F597F4D21A56D5F: "Swift 2.2 Release Signing Key <swift-infrastructure@swift.org>" not changed
2022-05-27T01:03:23.0848436Z gpg: key D441C977412B37AD: "Swift Automatic Signing Key #1 <swift-infrastructure@swift.org>" not changed
2022-05-27T01:03:23.0849465Z gpg: Total number processed: 8
2022-05-27T01:03:23.0850242Z gpg:              unchanged: 8
2022-05-27T01:03:23.6838983Z [command]/usr/bin/gpg --verify /home/runner/work/_temp/19cd8f86-def8-4a2a-8d13-13740de149ba /home/runner/work/_temp/f108991b-9d8c-4f2d-b601-09bcfb17f4f3
2022-05-27T01:03:23.6879784Z gpg: no valid OpenPGP data found.
2022-05-27T01:03:23.6880922Z gpg: the signature could not be verified.
2022-05-27T01:03:23.6881210Z Please remember that the signature file (.sig or .asc)
2022-05-27T01:03:23.6881490Z should be the first file given on the command line.
2022-05-27T01:03:23.6926331Z ##[error]Unexpected error, unable to continue. Please report at https://github.com/swift-actions/setup-swift/issues
The process '/usr/bin/gpg' failed with exit code 2
Stacktrace:
Error: The process '/usr/bin/gpg' failed with exit code 2
    at ExecState._setResult (/home/runner/work/_actions/swift-actions/setup-swift/v1/dist/index.js:995:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/swift-actions/setup-swift/v1/dist/index.js:978:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/swift-actions/setup-swift/v1/dist/index.js:872:27)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

**Workflow configuration (please complete the following information):**
 - Platform (`runs-on`): [macos-latest, ubuntu-latest]
 - Swift version (`swift-version`): [5.0, 5.1]

**Comment by Samasaur1** [comment]
This also happens for me with Swift 4.2 on `ubuntu-18.04` (which I believe is currently `ubuntu-latest`)

**Comment by Samasaur1** [comment]
I also cannot get any versions of Swift before 5.5 (4.2, 5.0, 5.1, 5.2, 5.3, 5.4) to work on `macos-11` or `macos-12`, although they do work on `macos-10.15`. I suspect part of those problems are specific to my project, but some of them may be an issue with this action

**Comment by adam-fowler** [comment]
I am seeing this with Swift 5.5 and 5.6

**Comment by soumyamahunt** [comment]
Seeing this in 5.6 and 5.7 as well.
