### ISSUE TITLE
"Operation was cancelled" for Swift 5.6.1 and macos-latest

### ISSUE THREAD

**Issue by Stiivi** [swift-actions/setup-swift#440]
**Describe the bug**

The Run action fails with:

```
Evaluating condition for step: 'Run swift-actions/setup-swift@v1'
Evaluating: success()
Evaluating success:
=> true
Result: true
Starting: Run swift-actions/setup-swift@v1
Loading inputs
Evaluating: matrix.swift
Evaluating Index:
..Evaluating matrix:
..=> Object
..Evaluating String:
..=> 'swift'
=> '5.6.1'
Result: '5.6.1'
Loading env
Run swift-actions/setup-swift@v1
with:
  swift-version: 5.6.1

Resolved range 5.6.1
Found matching version 5.6.1
[command]/usr/bin/xcrun --toolchain swift 5.6.1 --run swift --version
swift-driver version: 1.26.21 Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
Target: x86_64-apple-macosx11.0
isExplicit: 5.6.1
explicit? true
checking cache: /Users/runner/hostedtoolcache/swift-macOS/5.6.1/x64
not found
No matching installation found
Downloading swift for macOS
Downloading https://swift.org/builds/swift-5.6.1-release/xcode/swift-5.6.1-RELEASE/swift-5.6.1-RELEASE-osx.pkg
Destination /Users/runner/work/_temp/c28bbc06-fd4f-45a7-9442-52a9eb2f73ba
download complete
Extracting package
[command]/usr/bin/xar -x -C /Users/runner/work/_temp/a31b7349-775c-4edc-9336-903f730fdb64 -f /Users/runner/work/_temp/c28bbc06-fd4f-45a7-9442-52a9eb2f73ba -v
Re-evaluate condition on job cancellation for step: 'Run swift-actions/setup-swift@v1'.
The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at GitHub.Runner.Sdk.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at GitHub.Runner.Common.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at GitHub.Runner.Worker.Handlers.DefaultStepHost.ExecuteAsync(IExecutionContext context, String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, String standardInInput, CancellationToken cancellationToken)
   at GitHub.Runner.Worker.Handlers.NodeScriptActionHandler.RunAsync(ActionRunStage stage)
   at GitHub.Runner.Worker.ActionRunner.RunAsync()
   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
Finishing: Run swift-actions/setup-swift@v1
```

[Link to log](https://github.com/Stiivi/Flows/runs/7436304441?check_suite_focus=true)

**Workflow configuration (please complete the following information):**
 - Platform (`runs-on`): [ubuntu-latest, macos-latest]
 - Swift version (`swift-version`): ["5.6.1"]

Full configuration file is here: [swift.yml](https://github.com/Stiivi/Flows/blob/2727cc224f089f3de76bb1f6faf16e9cde007bee/.github/workflows/swift.yml).

**Comment by Stiivi** [comment]
This issue seems to be caused by #439 failing. When ubuntu was removed, the macos version was failing on the same error - "Missing Package.swift". Closing this one.

**Comment by rocxteady** [comment]
Check this out: [https://github.com/swift-actions/setup-swift/issues/439#issuecomment-1759614780](url)
