### ISSUE TITLE
Swift 5.7 isn't supported

### ISSUE THREAD

**Issue by wadetregaskis** [swift-actions/setup-swift#446]
Run swift-actions/setup-swift@v1
Error: Unexpected error, unable to continue. Please report at https://github.com/swift-actions/setup-swift/issues
Version "5.7" is not available
Stacktrace:
Error: Version "5.7" is not available
    at Object.verify (/Users/runner/work/_actions/swift-actions/setup-swift/v1/dist/index.js:9351:15)
    at /Users/runner/work/_actions/swift-actions/setup-swift/v1/dist/index.js:2755:36
    at Generator.next (<anonymous>)
    at fulfilled (/Users/runner/work/_actions/swift-actions/setup-swift/v1/dist/index.js:2736:58)

**Comment by keith** [comment]
++ it would be nice to have some beta support or something before it's released
