### ISSUE TITLE
The process `/usr/bin/gpg` failed with exit code 2

### ISSUE THREAD

**Issue by fwcd** [swift-actions/setup-swift#592]
**Describe the bug**

The step

```yaml
- name: Install Swift
  uses: swift-actions/setup-swift@v1
  with:
    swift-version: '5.8'
```

fails on `ubuntu-latest` with the following error:

```
 /usr/bin/gpg --import /home/runner/work/_temp/c34cb312-c194-4c69-9454-3ddec91b539a
gpg: directory '/home/runner/.gnupg' created
gpg: keybox '/home/runner/.gnupg/pubring.kbx' created
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
Error: Unexpected error, unable to continue. Please report at https://github.com/swift-actions/setup-swift/issues
The process '/usr/bin/gpg' failed with exit code 2
Stacktrace:
Error: The process '/usr/bin/gpg' failed with exit code 2
    at ExecState._setResult (/home/runner/work/_actions/swift-actions/setup-swift/v1/dist/index.js:3294:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/swift-actions/setup-swift/v1/dist/index.js:3277:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/swift-actions/setup-swift/v1/dist/index.js:3171:27)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

For the full log, see https://github.com/fwcd/swift-dns-service-discovery/actions/runs/5895114699/job/15990222238.

**Workflow configuration (please complete the following information):**
 - Action version (`uses`): `swift-actions/setup-swift@v1`
 - Platform (`runs-on`): `ubuntu-latest`
 - Swift version (`swift-version`): `5.8`

**Comment by fwcd** [comment]
Ah, looks like a duplicate of #591
