### ISSUE TITLE
Swift 5.8 or 5.9 not available on macOS latest? 

### ISSUE THREAD

**Issue by oschrenk** [swift-actions/setup-swift#607]
**Describe the bug**
```
Error: Unexpected error, unable to continue. Please report at https://github.com/swift-actions/setup-swift/issues
Version "[5](https://github.com/oschrenk/keyboard.swift/actions/runs/6530881897/job/17731014613?pr=4#step:2:6).9" is not available
Stacktrace:
Error: Version "5.9" is not available
    at Object.verify (/Users/runner/work/_actions/swift-actions/setup-swift/v1.17.0/dist/index.js:9988:15)
    at /Users/runner/work/_actions/swift-actions/setup-swift/v1.17.0/dist/index.js:3149:3[6](https://github.com/oschrenk/keyboard.swift/actions/runs/6530881897/job/17731014613?pr=4#step:2:7)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/runner/work/_actions/swift-actions/setup-swift/v1.1[7](https://github.com/oschrenk/keyboard.swift/actions/runs/6530881897/job/17731014613?pr=4#step:2:8).0/dist/index.js:3129:5[8](https://github.com/oschrenk/keyboard.swift/actions/runs/6530881897/job/17731014613?pr=4#step:2:9))
```

**Workflow configuration (please complete the following information):**
```
name: Swift

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["5.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v1.17.0
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
```

I also tried with swift `5.8` which also does not work. The latest version that is available is `5.7`. The README indicates that it should be 5.9.

**Comment by oschrenk** [comment]
My mistake. It took the example version from the readme 1.17.0 and not the actual latest release as the version for the action.

With 1.25.0 it works.
