### ISSUE TITLE
Unexpected error (possibly related to `gpg`)

### ISSUE THREAD

**Issue by Mr-Alirezaa** [swift-actions/setup-swift#666]
**Describe the bug**
Here is the log of the job failing unexpectedly.

```
2024-03-06T08:56:38.1628067Z Current runner version: '2.314.1'
2024-03-06T08:56:38.1651091Z ##[group]Operating System
2024-03-06T08:56:38.1651716Z Ubuntu
2024-03-06T08:56:38.1652157Z 22.04.4
2024-03-06T08:56:38.1652660Z LTS
2024-03-06T08:56:38.1652986Z ##[endgroup]
2024-03-06T08:56:38.1653436Z ##[group]Runner Image
2024-03-06T08:56:38.1653847Z Image: ubuntu-22.04
2024-03-06T08:56:38.1654246Z Version: 20240225.1.0
2024-03-06T08:56:38.1655286Z Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240225.1/images/ubuntu/Ubuntu2204-Readme.md
2024-03-06T08:56:38.1656686Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240225.1
2024-03-06T08:56:38.1657551Z ##[endgroup]
2024-03-06T08:56:38.1658023Z ##[group]Runner Image Provisioner
2024-03-06T08:56:38.1658463Z 2.0.359.1
2024-03-06T08:56:38.1658797Z ##[endgroup]
2024-03-06T08:56:38.1659835Z ##[group]GITHUB_TOKEN Permissions
2024-03-06T08:56:38.1661384Z Contents: read
2024-03-06T08:56:38.1661822Z Metadata: read
2024-03-06T08:56:38.1662464Z Packages: read
2024-03-06T08:56:38.1663006Z ##[endgroup]
2024-03-06T08:56:38.1666442Z Secret source: Actions
2024-03-06T08:56:38.1667065Z Prepare workflow directory
2024-03-06T08:56:38.2284433Z Prepare all required actions
2024-03-06T08:56:38.2445439Z Getting action download info
2024-03-06T08:56:38.3987261Z Download action repository 'swift-actions/setup-swift@v1' (SHA:cdbe0f7f4c77929b6580e71983e8606e55ffe7e4)
2024-03-06T08:56:38.6926512Z Download action repository 'actions/checkout@v4' (SHA:b4ffde65f46336ab88eb53be808477a3936bae11)
2024-03-06T08:56:38.8652658Z Complete job name: Swift 5.9 on ubuntu-latest
2024-03-06T08:56:38.9529087Z ##[group]Run swift-actions/setup-swift@v1
2024-03-06T08:56:38.9529728Z with:
2024-03-06T08:56:38.9530194Z   swift-version: 5.9
2024-03-06T08:56:38.9530606Z ##[endgroup]
2024-03-06T08:56:39.7438533Z [command]/usr/bin/gpg --import /home/runner/work/_temp/7c26a8bf-cc0c-4006-a903-dd6a0c72e721
2024-03-06T08:56:39.7534036Z gpg: directory '/home/runner/.gnupg' created
2024-03-06T08:56:39.7536569Z gpg: keybox '/home/runner/.gnupg/pubring.kbx' created
2024-03-06T08:56:39.7544413Z gpg: no valid OpenPGP data found.
2024-03-06T08:56:39.7545591Z gpg: Total number processed: 0
2024-03-06T08:56:39.7599767Z ##[error]Unexpected error, unable to continue. Please report at https://github.com/swift-actions/setup-swift/issues
The process '/usr/bin/gpg' failed with exit code 2
Stacktrace:
Error: The process '/usr/bin/gpg' failed with exit code 2
    at ExecState._setResult (/home/runner/work/_actions/swift-actions/setup-swift/v1/dist/index.js:3298:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/swift-actions/setup-swift/v1/dist/index.js:3281:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/swift-actions/setup-swift/v1/dist/index.js:3175:27)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
2024-03-06T08:56:39.7900888Z Cleaning up orphan processes
```

**Workflow configuration (please complete the following information):**
 - Action version (`uses`): swift-actions/setup-swift@v1
 - Platform (`runs-on`): ubuntu-latest
 - Swift version (`swift-version`): 5.9

**Comment by Mr-Alirezaa** [comment]
@angelapwen Issue is fixed. Thank you.
