### ISSUE TITLE
Version 6.0 is unavailable

### ISSUE THREAD

**Issue by fwcd** [swift-actions/setup-swift#683]
Swift 6.0 has been released, so it would be nice if it could be added:

```
Run swift-actions/setup-swift@v2
Error: Unexpected error, unable to continue. Please report at https://github.com/swift-actions/setup-swift/issues
Version "6.0" is not available
Stacktrace:
Error: Version "6.0" is not available
    at Object.verify (/Users/runner/work/_actions/swift-actions/setup-swift/v2/dist/index.js:572:15)
    at run (/Users/runner/work/_actions/swift-actions/setup-swift/v2/dist/index.js:329:32)
```

**Comment by master-bytes-krafter** [comment]
Hello, any aproximate estimation on when will swift 6 be available ?

**Comment by briannadoubt** [comment]
Meow? This has been out for a while and would be really helpful to have. Please respond!

**Comment by fwcd** [comment]
Fwiw, my workaround is to run the action in a `swift:6` container, but since that's not always feasible, it would be really nice to have this action updated too.

**Comment by briannadoubt** [comment]
Saw a PR up for this and a comment on there for a workaround - setting the macOS version to `macOS-15`. I've done this, and it works okay in the meantime.

**Comment by eonist** [comment]
Would love this too 🙏

**Comment by jcs090218** [comment]
Would need this too: https://github.com/the-flx/FlxSwift/actions/runs/12533956068/job/34954237053#step:2:5.

**Comment by danpalmer** [comment]
> Saw a PR up for this and a comment on there for a workaround - setting the macOS version to macOS-15. I've done this, and it works okay in the meantime.

Sadly that doesn't work for Swift on Linux, which is likely the primary use-case for this action, give the macOS runners have Swift available anyway.

**Comment by sjml** [comment]
Are any maintainers reading this? Would it be possible to get an ETA on this? Or should we fork/workaround/etc?

**Comment by danpalmer** [comment]
I've not seen anything from owners since July, pinged the original dev on Mastodon to see if they're still interested in maintaining this or possibly open it up to some other regular contributors.

**Comment by eonist** [comment]
It's literally is pinning the entire world to swift 5.9 😅 Apple is wondering why no one is using swift 6.0 😂

**Comment by fwal** [comment]
Fixed in #684 and deployed in version 2.2.0
