### ISSUE TITLE
gpg: refreshing 9 keys from hkp://keyserver.ubuntu.com gpg: keyserver refresh failed: Connection timed out -- due to an Ubuntu outage

### ISSUE THREAD

**Issue by jsoref** [swift-actions/setup-swift#687]
**Describe the bug**

GitHub runners are having trouble talking to the ubuntu keyserver, this is due to an [Ubuntu outage](https://status.canonical.com/#/incident/KNms6QK9ewuzz-7xUsPsNylV20jEt5kyKsd8A-3ptQGfIWu5y7ZGT1VoS9xYaudbp3Sc3OmbsoWVvJVlPw_WpA==).

If this is going to be a long term problem, and this were my action, I'd probably add code to detect the server being broken and provide a message, or consider not relying on it or something. At the very least, I'd open a ticket so people could see that it's a known issue.

I'm not sure that there's anything that setup-swift can do about this, but i'm not sure that there isn't, and the action says to report it:

[Export file baseline information (ubuntu-latest, nightly-latest)](https://github.com/check-spelling-sandbox/github-codeql-action/actions/runs/11717020444/job/32636039849#step:6:110)
> Unexpected error, unable to continue.
> Please report at https://github.com/swift-actions/setup-swift/issues
> Failed to refresh keys from any server in the pool.
```
Stacktrace: Error: Failed to refresh keys from any server in the pool.
 at refreshKeys (/home/runner/work/_actions/redsun82/setup-swift/362f49f31da2f5f4f851657046bdd1290d03edc8/dist/index.js:109:11)
 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 at async setupKeys (/home/runner/work/_actions/redsun82/setup-swift/362f49f31da2f5f4f851657046bdd1290d03edc8/dist/index.js:85:5)
 at async Object.install (/home/runner/work/_actions/redsun82/setup-swift/362f49f31da2f5f4f851657046bdd1290d03edc8/dist/index.js:168:9)
 at async run (/home/runner/work/_actions/redsun82/setup-swift/362f49f31da2f5f4f851657046bdd1290d03edc8/dist/index.js:335:17)
```

**Workflow configuration (please complete the following information):**
 - Action version (`uses`): redsun82/setup-swift@362f49f31da2f5f4f851657046bdd1290d03edc8 -- yes, I know, this isn't your version of the action, but afaict your version and that fork are effectively identical, and @redsun82 didn't update their fork not to say to file tickets here, so, ...
 - Platform (`runs-on`): ubuntu-latest
 - Swift version (`swift-version`): 5.10.1

```
Download action repository 'redsun82/setup-swift@362f49f31da2f5f4f851657046bdd1290d03edc8' (SHA:362f49f31da2f5f4f851657046bdd1290d03edc8)
Run ./../action/.github/actions/setup-swift
Run SWIFT_EXTRACTOR_DIR="$("$CODEQL_PATH" resolve languages --format json | jq -r '.swift[0]')"
version=5.10.1
Run redsun82/setup-swift@362f49f31da2f5f4f851657046bdd1290d03edc8
/usr/bin/gpg --import /home/runner/work/_temp/90e05948-43cd-4ef7-8a6a-4870cc96060e
gpg: directory '/home/runner/.gnupg' created
gpg: keybox '/home/runner/.gnupg/pubring.kbx' created
gpg: /home/runner/.gnupg/trustdb.gpg: trustdb created
gpg: key D441C977412B37AD: public key "Swift Automatic Signing Key #1 <swift-infrastructure@swift.org>" imported
gpg: key 9F597F4D21A56D5F: public key "Swift 2.2 Release Signing Key <swift-infrastructure@swift.org>" imported
gpg: key 63BC1CFE91D306C6: public key "Swift 3.x Release Signing Key <swift-infrastructure@swift.org>" imported
gpg: key EF5430F071E1B235: public key "Swift 4.x Release Signing Key <swift-infrastructure@swift.org>" imported
gpg: key 7638F1FB2B2B08C4: public key "Swift Automatic Signing Key #2 <swift-infrastructure@swift.org>" imported
gpg: key 925CC1CCED3D1561: public key "Swift 5.x Release Signing Key <swift-infrastructure@swift.org>" imported
gpg: key FAF6989E1BC16FEA: public key "Swift Automatic Signing Key #3 <swift-infrastructure@swift.org>" imported
gpg: key 925CC1CCED3D1561: "Swift 5.x Release Signing Key <swift-infrastructure@swift.org>" 1 new signature
gpg: key F167DF1ACF9CE069: public key "Swift Automatic Signing Key #4 <swift-infrastructure@forums.swift.org>" imported
gpg: key 925CC1CCED3D1561: "Swift 5.x Release Signing Key <swift-infrastructure@swift.org>" 1 new signature
gpg: key F167DF1ACF9CE069: "Swift Automatic Signing Key #4 <swift-infrastructure@forums.swift.org>" 1 new signature
gpg: key EF80A866B47A981F: public key "Swift 6.x Release Signing Key <swift-infrastructure@forums.swift.org>" imported
gpg: Total number processed: 12
gpg:               imported: 9
gpg:         new signatures: 3
/usr/bin/gpg --keyserver hkp://keyserver.ubuntu.com --refresh-keys Swift
gpg: refreshing 9 keys from hkp://keyserver.ubuntu.com
gpg: keyserver refresh failed: Connection timed out
Warning: An error occurred when trying to refresh keys from hkp://keyserver.ubuntu.com: Error: The process '/usr/bin/gpg' failed with exit code 2
/usr/bin/gpg --keyserver hkp://keyserver.ubuntu.com --refresh-keys Swift
gpg: refreshing 9 keys from hkp://keyserver.ubuntu.com
gpg: keyserver refresh failed: Connection timed out
Warning: An error occurred when trying to refresh keys from hkp://keyserver.ubuntu.com: Error: The process '/usr/bin/gpg' failed with exit code 2
Error: Unexpected error, unable to continue. Please report at https://github.com/swift-actions/setup-swift/issues
Failed to refresh keys from any server in the pool.
Stacktrace:
Error: Failed to refresh keys from any server in the pool.
    at refreshKeys (/home/runner/work/_actions/redsun82/setup-swift/362f49f31da2f5f4f851657046bdd1290d03edc8/dist/index.js:109:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async setupKeys (/home/runner/work/_actions/redsun82/setup-swift/362f49f31da2f5f4f85
    at async Object.install (/home/runner/work/_actions/redsun82/setup-swift/362f49f31da2f5f4f851657046bdd1290d03edc8/dist/index.js:168:9)
    at async run (/home/runner/work/_actions/redsun82/setup-swift/362f49f31da2f5f4f851657046bdd1290d03edc8/dist/index.js:335:17)
```

**Comment by fwal** [comment]
Will close - please reopen if issue persists
